'use client'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Provider } from 'react-redux'
import { ThemeProvider, createTheme } from '@mui/material'
import clsx from 'clsx'

import './home.css'
import store from '../../store'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

const theme = createTheme()

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <Provider store={store}>
      <ThemeProvider theme={theme}>
        <html lang="en">
          <body className={clsx(inter.className, 'container')}>{children}</body>
        </html>
      </ThemeProvider>
    </Provider>
  )
}

